enable build cache

diff --git a/.azure-pipelines/windows-build.yml b/.azure-pipelines/windows-build.yml
--- a/.azure-pipelines/windows-build.yml
+++ b/.azure-pipelines/windows-build.yml
@@ -29,18 +29,7 @@ steps:
 #     path: $(Pipeline.Workspace)/modules
 #     cacheHitVar: REPOSITORIES_CACHED
 #   displayName: Restore repository cache
-# 
-# # Copy libGL/libGLU into a place where they can be found during the
-# # build. We don't include system libraries so that we don't accidentally
-# # pick up libc and friends
-# - bash: |
-#     mkdir -p modules/lib
-#     cp -av /usr/lib/x86_64-linux-gnu/libGL.so* modules/lib
-#     cp -av /usr/lib/x86_64-linux-gnu/libGLU.so* modules/lib
-#   displayName: Set up GL/GLU libraries
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: eq(variables['Agent.OS'], 'Linux')
-# 
+
 # If other source repositories are not cached then download
 # them using the bootstrap script
 - powershell: |
@@ -87,32 +76,19 @@ steps:
   workingDirectory: $(Pipeline.Workspace)
 # condition: eq(variables.BASE_CACHED, 'false')
 
-# # Get a ready-made DIALS build directory from cache if available
-# # Allow day-to-day incremental cache updates
-# # Flush the cache once a week and whenever the environment specification
-# # or the bootstrap script is modified.
-# # Cache is not shared across operating systems and python versions
-# - task: Cache@2
-#   inputs:
-#     key: '"build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | ${{ parameters.conda_environment }} | "$(TODAY_ISO)"'
-#     restoreKeys: |
-#       "build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | ${{ parameters.conda_environment }}
-#     path: $(Pipeline.Workspace)/build
-#     cacheHitVar: BUILD_CACHED
-#   displayName: Restore cached build
-
-# # Copy GL/GLU/KHR headers into a place where they can be found during the
-# # build. We don't include system headers so that we don't accidentally
-# # pick up libc and friends
-# - bash: |
-#     set -e
-#     mkdir -p build/include
-#     cp -av /usr/include/GL build/include
-#     cp -av /usr/include/KHR build/include
-#   displayName: Set up GL/GLU headers
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: and(eq(variables.BUILD_CACHED, 'false'),
-#                  eq(variables['Agent.OS'], 'Linux'))
+# Get a ready-made DIALS build directory from cache if available
+# Allow day-to-day incremental cache updates
+# Flush the cache once a week and whenever the environment specification
+# or the bootstrap script is modified.
+# Cache is not shared across operating systems and python versions
+- task: Cache@2
+  inputs:
+    key: '"build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | ${{ parameters.conda_environment }} | "$(TODAY_ISO)"'
+    restoreKeys: |
+      "build" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | ${{ parameters.conda_environment }}
+    path: $(Pipeline.Workspace)/build
+    cacheHitVar: BUILD_CACHED
+  displayName: Restore cached build
 
 # If the build directory could not be loaded from cache then
 # create a new one using the bootstrap script
@@ -122,33 +98,35 @@ steps:
     REM for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
     REM popd
     REM call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64
+
+    REM -- the above can be used once we start using the default compiler suite. Until then we need to:
     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
+
     python modules/dials/installer/bootstrap.py build
-    REM cp -v dials build/activate  # ensure a copy is kept in the cache
+    copy dials.bat build\activate.bat  # ensure a copy is kept in the cache
   displayName: DIALS build (initial)
   workingDirectory: $(Pipeline.Workspace)
-# condition: eq(variables.BUILD_CACHED, 'false')
+  condition: eq(variables.BUILD_CACHED, 'false')
 
-- powershell: |
-    ls
-    ls modules
-    ls build
-    pwd
-  displayName: Print some info
-  failOnStderr: true
+# If the build directory was loaded (or kick-started) from cache then
+# do an incremental build
+- script: |
+    REM -- generic VS path setter, but only works if it is the only installation:
+    REM pushd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
+    REM for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
+    REM popd
+    REM call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64
+
+    REM -- the above can be used once we start using the default compiler suite. Until then we need to:
+    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
+
+    copy build\activate.bat dials.bat  # restore copy from the cache
+    call dials.bat
+    cd build
+    make reconf
+  displayName: DIALS build (incremental)
   workingDirectory: $(Pipeline.Workspace)
-
-# # If the build directory was loaded (or kick-started) from cache then
-# # do an incremental build
-# - bash: |
-#     set -e
-#     cp -v build/activate dials  # restore copy from the cache
-#     . dials
-#     cd build
-#     make reconf
-#   displayName: DIALS build (incremental)
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: ne(variables.BUILD_CACHED, 'false')
+  condition: ne(variables.BUILD_CACHED, 'false')
 
 # Ensure we are using up-to-date testing packages.
 # Extract the dials-data version so we can correctly cache regression data.
@@ -182,12 +160,14 @@ steps:
 #   displayName: Restore regression data cache
 
 - script: |
-    rem export DIALS_DATA=$(pwd)/data
+    echo set DIALS_DATA=$(pwd)/data
+    echo set DIALS_DATA=$(Pipeline.Workspace)/data
+    set PYTHONUNBUFFERED=TRUE
+
     call dials.bat
     cd modules/dials
-    set PYTHONUNBUFFERED=TRUE
-    echo pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
-    pytest -v -ra --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
+    echo pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 --timeout=5400
+    pytest -v -ra --timeout=5400 algorithms/indexing/test_compare_orientation_matrices.py || echo "##vso[task.complete result=Failed;]Some tests failed"
   displayName: Run some tests (temporary)
   workingDirectory: $(Pipeline.Workspace)
 
@@ -201,23 +181,21 @@ steps:
 #         --timeout=5400 --regression --runslow || echo "##vso[task.complete result=Failed;]Some tests failed"
 #   displayName: Run tests
 #   workingDirectory: $(Pipeline.Workspace)
-# 
-# # Recover disk space after testing
-# # This is only relevant if we had cache misses, as free disk space is required to create cache archives
-# - bash: |
-#     echo Disk space usage:
-#     du -sh *
-#     echo
-#     echo Test artefacts:
-#     du -h tests
-#     rm -rf tests
-#   displayName: Recover disk space
-#   workingDirectory: $(Pipeline.Workspace)
-#   condition: or(ne(variables.BASE_CACHED, 'true'),
-#                 ne(variables.BUILD_CACHED, 'true'),
-#                 ne(variables.DATA_CACHED, 'true'),
-#                 ne(variables.REPOSITORIES_CACHED, 'true'))
-# 
+
+# Recover disk space after testing
+# This is only relevant if we had cache misses, as free disk space is required to create cache archives
+- powershell: |
+    echo Disk space usage:
+    Get-ChildItem -Directory | ForEach-Object { "{1:N2} GB  {0:S}" -f $_, ((Get-ChildItem $_ -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -sum).sum / 1Gb) }
+#   Remove-Item -Path tests -Recurse
+  displayName: Recover disk space
+  workingDirectory: $(Pipeline.Workspace)
+  condition: ne(variables.BUILD_CACHED, 'true')
+# condition: or(ne(variables.BASE_CACHED, 'true'),
+#               ne(variables.BUILD_CACHED, 'true'),
+#               ne(variables.DATA_CACHED, 'true'),
+#               ne(variables.REPOSITORIES_CACHED, 'true'))
+
 # # If the downloaded repositories are to be cached then clean them up before the
 # # snapshot is made
 # - bash: |
