test build cache

diff --git a/.azure-pipelines/windows-build.yml b/.azure-pipelines/windows-build.yml
--- a/.azure-pipelines/windows-build.yml
+++ b/.azure-pipelines/windows-build.yml
@@ -162,14 +162,12 @@ steps:
 #   displayName: Restore regression data cache
 
 - script: |
-    echo set DIALS_DATA=$(pwd)/data
-    echo set DIALS_DATA=$(Pipeline.Workspace)/data
+    set DIALS_DATA=$(Pipeline.Workspace)\data
     set PYTHONUNBUFFERED=TRUE
 
     call dials.bat
     cd modules/dials
-    echo pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)/tests" --durations=10 --timeout=5400
-    pytest -v -ra --timeout=5400 algorithms/indexing/test_compare_orientation_matrices.py || echo "##vso[task.complete result=Failed;]Some tests failed"
+    pytest -v -ra  -n auto --basetemp="$(Pipeline.Workspace)\tests" --durations=10 --timeout=5400 test/command_line/test_merge_reflection_lists.py algorithms/indexing/test_compare_orientation_matrices.py || echo "##vso[task.complete result=Failed;]Some tests failed"
   displayName: Run some tests (temporary)
   workingDirectory: $(Pipeline.Workspace)
 
