Disable environment cache, test repository cache

diff --git a/.azure-pipelines/windows-build.yml b/.azure-pipelines/windows-build.yml
--- a/.azure-pipelines/windows-build.yml
+++ b/.azure-pipelines/windows-build.yml
@@ -6,10 +6,11 @@
 
 steps:
 
-- script: |
-    choco install microsoft-visual-cpp-build-tools
-  displayName: Install MSVC 2015 Build Tools
-  # can't use vs2017+ yet, as cbflib_adaptbx won't build
+# Downgrade the installed vs2017+ to 2015, as cbflib_adaptbx won't build otherwise
+# This takes up 5 minutes of uncacheable build time :(
+#- script: |
+#    choco install microsoft-visual-cpp-build-tools
+#  displayName: Install MSVC 2015 Build Tools
 
 # Obtain a shallow clone of the DIALS repository.
 # DIALS will not be able to report proper version numbers
@@ -18,17 +19,17 @@ steps:
   fetchDepth: 1
   displayName: Checkout $(Build.SourceBranch)
 
-# # Get all other source repositories from cache if available
-# # Allow day-to-day incremental cache updates
-# # Flush the cache once a week and whenever the bootstrap script is modified
-# - task: Cache@2
-#   inputs:
-#     key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "$(TODAY_ISO)"'
-#     restoreKeys: |
-#       "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py
-#     path: $(Pipeline.Workspace)/modules
-#     cacheHitVar: REPOSITORIES_CACHED
-#   displayName: Restore repository cache
+# Get all other source repositories from cache if available
+# Allow day-to-day incremental cache updates
+# Flush the cache once a week and whenever the bootstrap script is modified
+- task: Cache@2
+  inputs:
+    key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "$(TODAY_ISO)"'
+    restoreKeys: |
+      "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py
+    path: $(Pipeline.Workspace)/modules
+    cacheHitVar: REPOSITORIES_CACHED
+  displayName: Restore repository cache
 
 # If other source repositories are not cached then download
 # them using the bootstrap script
@@ -39,34 +40,34 @@ steps:
   displayName: Repository checkout (initial)
   failOnStderr: true
   workingDirectory: $(Pipeline.Workspace)
-#  condition: eq(variables.REPOSITORIES_CACHED, 'false')
+  condition: eq(variables.REPOSITORIES_CACHED, 'false')
 
-# # Update the cctbx_project and dxtbx repositories now,
-# # unless they were just freshly cloned
-# - bash: |
-#     set -e
-#     for repository in cctbx_project dxtbx; do
-#       echo ""
-#       echo "Checking out latest ${repository} commit"
-#       cd $(Pipeline.Workspace)/modules/${repository}
-#       git fetch origin master --depth=1
-#       git checkout FETCH_HEAD
-#     done
-#   displayName: Repository update (incremental)
-#   condition: ne(variables.REPOSITORIES_CACHED, 'false')
+# Update the cctbx_project and dxtbx repositories now,
+# unless they were just freshly cloned
+- script: |
+    FOR %%REPOSITORY IN (cctbx_project dxtbx) DO (
+      echo ""
+      echo "Checking out latest %%REPOSITORY commit"
+      cd $(Pipeline.Workspace)/modules/%%REPOSITORY
+      git fetch origin master --depth=1
+      git checkout FETCH_HEAD
+    )
+  displayName: Repository update (incremental)
+  condition: ne(variables.REPOSITORIES_CACHED, 'false')
 
-# Get a ready-made DIALS conda environment from cache if available
-# Allow day-to-day incremental cache updates
-# Flush the cache once a week and whenever the environment specification is modified
-# Cache is not shared across operating systems and python versions
-- task: Cache@2
-  inputs:
-    key: '"base!E2" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | ${{ parameters.conda_environment }} | "$(TODAY_ISO)"'
-    restoreKeys: |
-      "base!E2" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | ${{ parameters.conda_environment }}
-    path: $(Pipeline.Workspace)/conda_base
-    cacheHitVar: BASE_CACHED
-  displayName: Restore environment cache
+# # Get a ready-made DIALS conda environment from cache if available
+# # Allow day-to-day incremental cache updates
+# # Flush the cache once a week and whenever the environment specification is modified
+# # Cache is not shared across operating systems and python versions
+# # # Disabled as the generated cache is unrestorable due to some link issues
+# - task: Cache@2
+#   inputs:
+#     key: '"base" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | ${{ parameters.conda_environment }} | "$(TODAY_ISO)"'
+#     restoreKeys: |
+#       "base" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | "$(Agent.OS)-$(Agent.Version)" | "$(PYTHON_VERSION)" | ${{ parameters.conda_environment }}
+#     path: $(Pipeline.Workspace)/conda_base
+#     cacheHitVar: BASE_CACHED
+#   displayName: Restore environment cache
 
 # If the conda environment could not be loaded from cache then
 # create a new one using the bootstrap script
@@ -74,7 +75,7 @@ steps:
     python modules/dials/installer/bootstrap.py base --python $(PYTHON_VERSION)
   displayName: Create python $(PYTHON_VERSION) environment
   workingDirectory: $(Pipeline.Workspace)
-  condition: eq(variables.BASE_CACHED, 'false')
+# condition: eq(variables.BASE_CACHED, 'false')
 
 # Get a ready-made DIALS build directory from cache if available
 # Allow day-to-day incremental cache updates
@@ -129,7 +130,7 @@ steps:
     make
   displayName: DIALS build (incremental)
   workingDirectory: $(Pipeline.Workspace)
-  condition: ne(variables.BUILD_CACHED, 'false')
+  condition: eq(variables.BUILD_CACHED, 'never')
 
 # Ensure we are using up-to-date testing packages.
 # Extract the dials-data version so we can correctly cache regression data.
@@ -168,7 +169,7 @@ steps:
 
     call dials.bat
     cd modules/dials
-    pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)\tests" --durations=10 --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
+    REM   pytest -v -ra -n auto --basetemp="$(Pipeline.Workspace)\tests" --durations=10 --timeout=5400 || echo "##vso[task.complete result=Failed;]Some tests failed"
   displayName: Run some tests (temporary)
   workingDirectory: $(Pipeline.Workspace)
 
@@ -210,39 +211,36 @@ steps:
   displayName: Recover disk space
   workingDirectory: $(Pipeline.Workspace)
 # condition: or(ne(variables.BASE_CACHED, 'true'),
-#               ne(variables.BUILD_CACHED, 'true'))
-# condition: or(ne(variables.BASE_CACHED, 'true'),
 #               ne(variables.BUILD_CACHED, 'true'),
 #               ne(variables.DATA_CACHED, 'true'),
 #               ne(variables.REPOSITORIES_CACHED, 'true'))
 
-# # If the downloaded repositories are to be cached then clean them up before the
-# # snapshot is made
-# - bash: |
-#     set -e
-#     echo Preparing repository cache
-#     for repository in *; do
-#       if [[ "${repository}" == "dials" ]]; then
-#         echo "  - Skipping dials"
-#       elif [ -f ${repository} ]; then
-#         echo "  - Deleting file ${repository}"
-#         rm ${repository}
-#       elif [ -e ${repository}/.git ]; then
-#         if [[ "${repository}" == "cctbx_project" ]] || [[ "${repository}" == "dxtbx" ]]; then
-#           echo "  - Cleaning up ${repository}"
-#           cd ${repository}
-#           git reset --hard HEAD
-#           git clean -dffxq
-#           git repack -a -d
-#           cd -
-#         else
-#           echo "  - Removing version control from ${repository}"
-#           rm -rf ${repository}/.git
-#         fi
-#       fi
-#     done
-#     echo Completed
-#     ls -la
-#   displayName: Preparing cache
-#   workingDirectory: $(Pipeline.Workspace)/modules
-#   condition: ne(variables.REPOSITORIES_CACHED, 'true')
+# If the downloaded repositories are to be cached then clean them up before the
+# snapshot is made
+- powershell: |
+    echo "Preparing repository cache"
+    Get-ChildItem | ForEach-Object {
+      if ($_.Name -match "dials") {
+        echo "  - Skipping dials"
+      } elseif ($_ -is [System.IO.FileInfo]) {
+        echo "  - Deleting file $_.Name"
+        Remove-Item $_
+      } elseif (Test-Path -Path (Join-Path -Path $_ -ChildPath "git")) {
+        if (($_.Name -match "cctbx_project") -or ($_.Name -match "dxtbx")) {
+          echo "  - Cleaning up $_.Name"
+          cd (Join-Path -Path $_ -ChildPath "git")
+          git reset --hard HEAD
+          git clean -dffxq
+          git repack -a -d
+          cd ..\..
+        } else {
+          echo "  - Removing version control from $_.Name"
+          Remove-Item -Path (Join-Path -Path $_ -ChildPath "git") -Recurse -Force
+        }
+      }
+    }
+    echo "Completed"
+    dir
+  displayName: Preparing cache
+  workingDirectory: $(Pipeline.Workspace)/modules
+  condition: ne(variables.REPOSITORIES_CACHED, 'true')
